version: '3.8'

services:

  app:
    image: ghcr.io/configuralo-it/app/app:${APP_VERSION}

    networks:
      - app
      - maria

    volumes:
      - storage:/var/www/html/storage

    secrets:
      - source: app_env
        target: /var/www/html/.env

networks:
  app:
  maria:

volumes:
  storage:

secrets:
  app_env:
    external: true
