version: '3.8'

services:

  schedule:
    depends_on:
      - app

    image: ghcr.io/configuralo-it/app/schedule:${SCHEDULE_VERSION}

    networks:
      - maria

    volumes:
      - storage:/var/www/html/storage

    secrets:
      - source: app_env
        target: /var/www/html/.env

networks:
  maria:

secrets:
  app_env:
    external: true
