version: '3.8'

services:

  webserver:
    depends_on:
      - app

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.constraint-label=traefik
        - traefik.http.services.app-webserver.loadbalancer.server.port=80

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # - traefik.http.middlewares.app-webserver-auth.basicauth.users=root:${WEBSERVER_HASHED_PASSWORD}

        # Router: HTTP
        - traefik.http.routers.app-webserver-http.rule=Host(`${HOST}`)
        - traefik.http.routers.app-webserver-http.entrypoints=http
        - traefik.http.routers.app-webserver-http.middlewares=https-redirect

        # Router: HTTPS
        - traefik.http.routers.app-webserver-https.rule=Host(`${HOST}`)
        - traefik.http.routers.app-webserver-https.entrypoints=https
        - traefik.http.routers.app-webserver-https.tls=true
        - traefik.http.routers.app-webserver-https.tls.certresolver=le
        # - traefik.http.routers.app-webserver-https.middlewares=app-webserver-auth

    image: ghcr.io/configuralo-it/app/webserver:${WEBSERVER_VERSION}

    networks:
      - app
      - traefik

networks:
  app:
  traefik:
    external: true
