version: '3.8'

services:

  webserver:
    depends_on:
      - app

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.constraint-label=traefik
        - traefik.http.services.apps-web-app-webserver.loadbalancer.server.port=80

        - traefik.http.routers.apps-web-app-webserver-http.rule=Host(`localhost`)
        - traefik.http.routers.apps-web-app-webserver-http.entrypoints=http

    image: ghcr.io/appolabs/apps-web-app/webserver:${WEBSERVER_VERSION}

    networks:
      - app
      - traefik

networks:
  app:
  traefik:
    external: true
