name: release test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  make-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not dev
        if: github.ref != format('refs/heads/{0}', 'dev')
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than dev"
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate tag name
        run: |
          git fetch --tags

          year=$(date +'%y')
          month=$(date +'%m')
          day=$(date +'%d')
          week_of_month=$(( (10#$day - 1) / 7 ))
          latest_tag=$(git tag -l "v$year.$month.$week_of_month.*" --sort=-v:refname | head -n 1)

          if [ -z "$latest_tag" ]
          then
            release_index=$((0 + 1))
          else
            release_index=$(echo $latest_tag | awk -F '.' '{print $4}')
            release_index=$((release_index + 1))
          fi

          tag_name="v$year.$month.$week_of_month.$release_index"
          echo "tag_name=$tag_name" >> $GITHUB_ENV

      - name: Create tag
        run: |
          tag_name="${{ env.tag_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$tag_name" -m "test release"
          git push origin "$tag_name"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: ${{ env.tag_name }}
          prerelease: true

    outputs:
      tag-name: ${{ env.tag_name }}

  docker:
    needs: make-tag
    uses: configuralo-it/github-workflows/.github/workflows/app-docker.yml@master
    with:
      tag_name: ${{ needs.make-tag.outputs.tag-name }}
      test: true
    secrets:
      NOVA_EMAIL: ${{ secrets.NOVA_EMAIL }}
      NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
